# Generated by Django 5.0.7 on 2024-07-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_categories_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='dddd', max_length=50),
            preserve_default=False,
        ),
    ]
